### ISSUE TITLE
Show demo to end users

### ISSUE THREAD

**Issue by deebuls** [agrija9/Software-Development-Project#28]
Please show a demo to the following end users and take their feedback and report the feedbacks.

1. Dharmin
2. Santosh 
3. Alex 
4. Minh

**Comment by divindevaiah** [comment]
The feedback received are:

1. The shape of node can be changed from rectangle to triangle because on zooming into graph the rectangle seems to increase in size that gives a notion of its size conveying some information.

2. The message parser can be made extendable so that specific users can parse message types according to their usage.
